=== dvorkind/training/xml-task3/resources/components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dvorkin.by/components"
           xmlns="http://www.dvorkin.by/components" elementFormDefault="qualified">

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:minLength value="5"/>
            <xs:maxLength value="40"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="originType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z ]{3,20}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:pattern value="[0-9]+\.[0-9]{1,2}"/>
            <xs:minInclusive value="1.00"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="peripheralType">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:simpleType name="powerUsageType">
        <xs:restriction base="xs:decimal">
            <xs:pattern value="[0-9]+\.[0-9]{1,2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="hasCoolerType">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MONITOR"/>
            <xs:enumeration value="KEYBOARD"/>
            <xs:enumeration value="MOUSE"/>
            <xs:enumeration value="MOTHERBOARD"/>
            <xs:enumeration value="PROCESSOR"/>
            <xs:enumeration value="MEMORY"/>
            <xs:enumeration value="VIDEOCARD"/>
            <xs:enumeration value="STORAGE"/>
            <xs:enumeration value="POWERSUPPLY"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="portType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="HDMI"/>
            <xs:enumeration value="VGA"/>
            <xs:enumeration value="USB"/>
            <xs:enumeration value="SOCKET"/>
            <xs:enumeration value="PCI_E"/>
            <xs:enumeration value="SATA"/>
            <xs:enumeration value="IDE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="criticalType">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>

    <xs:simpleType name="componentID">
        <xs:restriction base="xs:ID">
            <xs:pattern value="C[1-9][0-9]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="parametersType">
        <xs:sequence>
            <xs:element name="peripheral" type="peripheralType"/>
            <xs:element name="powerUsage" type="powerUsageType" minOccurs="0"/>
            <xs:element name="hasCooler" type="hasCoolerType"/>
            <xs:element name="group" type="groupType"/>
            <xs:element name="port" type="portType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="componentType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <xs:element name="origin" type="originType"/>
            <xs:element name="price" type="priceType"/>
            <xs:element name="parameters" type="parametersType"/>
            <xs:element name="critical" type="criticalType"/>
        </xs:sequence>
        <xs:attribute name="id" type="componentID" use="required"/>
    </xs:complexType>

    <xs:element name="components">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="component" type="componentType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dvorkind/training/xml-task3/resources/output/processor.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C28">
    <name>Intel Core i5-10400F</name>
    <origin>USA</origin>
    <price>371.77</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>65.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>PROCESSOR</group>
      <port>SOCKET</port>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C5">
    <name>AMD Ryzen 5 3600</name>
    <origin>USA</origin>
    <price>452.08</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>65.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>PROCESSOR</group>
      <port>SOCKET</port>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C12">
    <name>Intel Xeon Gold 6256</name>
    <origin>USA</origin>
    <price>12151.8</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>205.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>PROCESSOR</group>
      <port>SOCKET</port>
    </parameters>
    <critical>true</critical>
  </component>
</components>

=== dvorkind/training/xml-task3/resources/output/monitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C1">
    <name>Samsung C24RG50FQI</name>
    <origin>Korea</origin>
    <price>471.97</price>
    <parameters>
      <peripheral>true</peripheral>
      <powerUsage>32.0</powerUsage>
      <hasCooler>false</hasCooler>
      <group>MONITOR</group>
      <port>HDMI</port>
    </parameters>
    <critical>false</critical>
  </component>
  <component id="C21">
    <name>LG 27UL500-W</name>
    <origin>Korea</origin>
    <price>708.68</price>
    <parameters>
      <peripheral>true</peripheral>
      <powerUsage>40.0</powerUsage>
      <hasCooler>false</hasCooler>
      <group>MONITOR</group>
      <port>HDMI</port>
    </parameters>
    <critical>false</critical>
  </component>
  <component id="C10">
    <name>Xiaomi Mi Surface Display 34"</name>
    <origin>China</origin>
    <price>1114.2</price>
    <parameters>
      <peripheral>true</peripheral>
      <powerUsage>54.0</powerUsage>
      <hasCooler>false</hasCooler>
      <group>MONITOR</group>
      <port>HDMI</port>
    </parameters>
    <critical>false</critical>
  </component>
</components>

=== dvorkind/training/xml-task3/resources/output/keyboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C2">
    <name>Logitech Corded Keyboard K280e</name>
    <origin>Swiss</origin>
    <price>35.37</price>
    <parameters>
      <peripheral>true</peripheral>
      <hasCooler>false</hasCooler>
      <group>KEYBOARD</group>
      <port>USB</port>
    </parameters>
    <critical>false</critical>
  </component>
  <component id="C25">
    <name>HyperX Alloy Origins (HyperX Red)</name>
    <origin>USA</origin>
    <price>294.26</price>
    <parameters>
      <peripheral>true</peripheral>
      <hasCooler>false</hasCooler>
      <group>KEYBOARD</group>
      <port>USB</port>
    </parameters>
    <critical>false</critical>
  </component>
  <component id="C14">
    <name>SteelSeries Apex 7 Linear Red</name>
    <origin>Denmark</origin>
    <price>479.8</price>
    <parameters>
      <peripheral>true</peripheral>
      <hasCooler>false</hasCooler>
      <group>KEYBOARD</group>
      <port>USB</port>
    </parameters>
    <critical>false</critical>
  </component>
</components>

=== dvorkind/training/xml-task3/resources/output/videocard.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C15">
    <name>Gigabyte GeForce GTX 1660 OC 6GB GDDR5</name>
    <origin>Taiwan</origin>
    <price>1125.0</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>450.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>VIDEOCARD</group>
      <port>PCI_E</port>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C7">
    <name>Palit GeForce RTX 3060 Dual 12GB GDDR6</name>
    <origin>Germany</origin>
    <price>1827.0</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>180.2</powerUsage>
      <hasCooler>true</hasCooler>
      <group>VIDEOCARD</group>
      <port>PCI_E</port>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C19">
    <name>Sapphire Radeon RX 6700 XT 12GB GDDR6</name>
    <origin>Hong Kong</origin>
    <price>2546.64</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>650.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>VIDEOCARD</group>
      <port>PCI_E</port>
    </parameters>
    <critical>true</critical>
  </component>
</components>

=== dvorkind/training/xml-task3/resources/output/memory.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C26">
    <name>Patriot Signature 2GB DDR2 PC2-6400</name>
    <origin>USA</origin>
    <price>35.88</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>1.8</powerUsage>
      <hasCooler>false</hasCooler>
      <group>MEMORY</group>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C20">
    <name>Kingston ValueRAM 4GB DDR3 PC3-12800</name>
    <origin>USA</origin>
    <price>82.62</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>1.5</powerUsage>
      <hasCooler>false</hasCooler>
      <group>MEMORY</group>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C24">
    <name>Samsung 8GB DDR4 SODIMM PC4-21300</name>
    <origin>Korea</origin>
    <price>127.29</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>1.2</powerUsage>
      <hasCooler>false</hasCooler>
      <group>MEMORY</group>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C6">
    <name>HyperX Fury 2x8GB DDR4 PC4-25600</name>
    <origin>USA</origin>
    <price>234.82</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>1.35</powerUsage>
      <hasCooler>false</hasCooler>
      <group>MEMORY</group>
    </parameters>
    <critical>true</critical>
  </component>
</components>

=== dvorkind/training/xml-task3/resources/output/powersupply.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C17">
    <name>AeroCool ECO-500W</name>
    <origin>Taiwan</origin>
    <price>53.72</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>500.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>POWERSUPPLY</group>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C11">
    <name>Zalman GigaMax ZM550-GVII</name>
    <origin>Korea</origin>
    <price>115.77</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>550.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>POWERSUPPLY</group>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C9">
    <name>Chieftec A-80 CTG-750C 750W</name>
    <origin>Germany</origin>
    <price>151.63</price>
    <parameters>
      <peripheral>false</peripheral>
      <powerUsage>750.0</powerUsage>
      <hasCooler>true</hasCooler>
      <group>POWERSUPPLY</group>
    </parameters>
    <critical>true</critical>
  </component>
</components>

=== dvorkind/training/xml-task3/resources/output/motherboard.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C4">
    <name>Gigabyte B450M S2H (rev. 1.0)</name>
    <origin>China</origin>
    <price>157.28</price>
    <parameters>
      <peripheral>false</peripheral>
      <hasCooler>false</hasCooler>
      <group>MOTHERBOARD</group>
      <port>SOCKET</port>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C13">
    <name>ASRock B460M Pro4</name>
    <origin>Taiwan</origin>
    <price>237.64</price>
    <parameters>
      <peripheral>false</peripheral>
      <hasCooler>false</hasCooler>
      <group>MOTHERBOARD</group>
      <port>SOCKET</port>
    </parameters>
    <critical>true</critical>
  </component>
  <component id="C22">
    <name>ASUS TUF Gaming B550-Plus</name>
    <origin>Taiwan</origin>
    <price>384.54</price>
    <parameters>
      <peripheral>false</peripheral>
      <hasCooler>false</hasCooler>
      <group>MOTHERBOARD</group>
    </parameters>
    <critical>true</critical>
  </component>
</components>

=== dvorkind/training/xml-task3/resources/output/mouse.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dvorkin.by/components" xsi:schemaLocation="http://www.dvorkin.by/components components.xsd">
  <component id="C27">
    <name>Canyon CND-SGM03RGB</name>
    <origin>Cyprus</origin>
    <price>19.71</price>
    <parameters>
      <peripheral>true</peripheral>
      <hasCooler>false</hasCooler>
      <group>MOUSE</group>
      <port>USB</port>
    </parameters>
    <critical>false</critical>
  </component>
  <component id="C3">
    <name>Razer DeathAdder Essential</name>
    <origin>USA</origin>
    <price>70.2</price>
    <parameters>
      <peripheral>true</peripheral>
      <hasCooler>false</hasCooler>
      <group>MOUSE</group>
      <port>USB</port>
    </parameters>
    <critical>false</critical>
  </component>
  <component id="C23">
    <name>Logitech G Pro Wireless</name>
    <origin>Swiss</origin>
    <price>271.26</price>
    <parameters>
      <peripheral>true</peripheral>
      <hasCooler>false</hasCooler>
      <group>MOUSE</group>
      <port>USB</port>
    </parameters>
    <critical>false</critical>
  </component>
</components>
